configReload:
  schedule: "*/5 * * * *"
  configUrl: https://raw.githubusercontent.com/facklambda/homebox/main/gitops/fetchit/config.yaml
    
targetConfigs:
- url: https://github.com/facklambda/homebox
  kube:
  - name: caddy
    targetPath: gitops/caddy
    schedule: "*/5 * * * *"
  branch: main

# - url: https://github.com/facklambda/homebox
#   kube:
#   - name: nginx
#     targetPath: gitops/nginx
#     schedule: "*/5 * * * *"
#   branch: main