configReload:
  schedule: "*/1 * * * *"
  configUrl: https://raw.githubusercontent.com/facklambda/homebox/main/gitops/fetchit/config.yaml
    
targetConfigs:
- url: https://github.com/facklambda/homebox
  kube:
  - name: caddy
    targetPath: gitops/caddy
    schedule: "*/1 * * * *"
    pullImage: true
  branch: main

